#!/bin/sh -e
#
# ==============================================================================
# PAQUETE: canaima-escritorio-gnome
# ARCHIVO: postrm
# DESCRIPCIÓN: Revierte los cambios hechos por el paquete en los scripts del
#	      mantenedor, de forma tal de asegurarse que el sistema quede
#	      como estaba antes de su instalación.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

ERROR() {
	printf "\033[1,31m${1}\033[0m\n"
}

ADVERTENCIA() {
	printf "\033[1,33m${1}\033[0m\n"
}

EXITO() {
	printf "\033[1,32m${1}\033[0m\n"
}

ALTERNATIVES="/etc/default/prelink /etc/default/rcS /etc/inittab /etc/xdg/user-dirs.defaults /etc/locale.nopurge /etc/adduser.conf /etc/NetworkManager/NetworkManager.conf"

case ${1} in
	purge|upgrade|remove|failed-upgrade|abort-install|abort-upgrade|disappear|'')
		for ALT in ${ALTERNATIVES}; do
			ALTNAME="$( basename "${ALT}" )"
			if which ucf >/dev/null; then
				ucf --debconf-ok --purge "/etc/canaima-escritorio-gnome/alternatives/${ALTNAME}"
			fi

			if which ucfr >/dev/null; then
				ucfr --purge canaima-base "/etc/canaima-escritorio-gnome/alternatives/${ALTNAME}"
			fi

			ADVERTENCIA "Removiendo alternativa para el archivo \"${ALT}\" ..."
			update-alternatives --remove "${ALTNAME}" "/etc/canaima-escritorio-gnome/alternatives/${ALTNAME}"
		done

	;;

	*)
		ERROR "postrm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
