#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-escritorio-gnome
# ARCHIVO: postrm
# DESCRIPCIÓN: Revierte los cambios hechos por el paquete en los scripts del
#              mantenedor, de forma tal de asegurarse que el sistema quede
#              como estaba antes de su instalación.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-escritorio-gnome"

# Color Verde
VERDE="\e[1;32m"
# Color Rojo
ROJO="\e[1;31m"
# Color Amarillo
AMARILLO="\e[1;33m"
# Negrita
BOLD="\e[1m"
# Caracter de fin de línea
FIN="\e[0m"

function ERROR() {
echo -e ${ROJO}${1}${FIN}
}

function ADVERTENCIA() {
echo -e ${AMARILLO}${1}${FIN}
}

function EXITO() {
echo -e ${VERDE}${1}${FIN}
}

case ${1} in

	purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

	ADVERTENCIA "Restaurando antiguo /etc/default/prelink.respaldo"
	[ -e /etc/default/prelink.respaldo ] && mv /etc/default/prelink.respaldo /etc/default/prelink

	ADVERTENCIA "Restaurando antiguo /etc/default/rcS.respaldo ..."
	[ -e /etc/default/rcS.respaldo ] && mv /etc/default/rcS.respaldo /etc/default/rcS

	ADVERTENCIA "Restaurando antiguo /etc/sysctl.conf.respaldo ..."
	[ -e /etc/sysctl.conf.respaldo ] && mv /etc/sysctl.conf.respaldo /etc/sysctl.conf

	ADVERTENCIA "Restaurando antiguo /etc/inittab.respaldo ..."
	[ -e /etc/inittab.respaldo ] && mv /etc/inittab.respaldo /etc/inittab

	;;

	*)

		echo "postrm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0

