#!/bin/sh -e
#
# ==============================================================================
# PAQUETE: canaima-escritorio-gnome
# ARCHIVO: postinst
# DESCRIPCIÓN: Configura el sistema despues la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

ERROR() {
	printf "\033[1;31m${1}\033[0m\n"
}

ADVERTENCIA() {
	printf "\033[1;33m${1}\033[0m\n"
}

EXITO() {
	printf "\033[1;32m${1}\033[0m\n"
}

ALTERNATIVES="/etc/default/prelink /etc/default/rcS /etc/inittab /etc/xdg/user-dirs.defaults /etc/locale.nopurge"

case ${1} in
	configure|'')

		for ALT in ${ALTERNATIVES}; do
			ALTNAME="$( basename "${ALT}" )"
			ADVERTENCIA "Añadiendo alternativa para el archivo \"${ALT}\" ..."
			update-alternatives --install "${ALT}" "${ALTNAME}" "/usr/share/canaima-escritorio-gnome/${ALTNAME}" 60
		done

		# ¿No existe la carpeta escritorio?
		if [ ! -d /etc/skel/Escritorio ]; then
			if [ -h /etc/skel/Escritorio ] || [ -f /etc/skel/Escritorio ]; then
				rm -rf /etc/skel/Escritorio
			fi

			mkdir -p /etc/skel/Escritorio
			ADVERTENCIA "Creando carpeta Escritorio en /etc/skel/ ..."
		fi 

		# ¿Existe un enlace simbólico llamado Desktop?
		# ¿Y una carpeta llamada Escritorio?
		if [ -h /etc/skel/Desktop ] && [ -d /etc/skel/Escritorio ]; then
			# Borra el enlace simbólico
			rm -rf /etc/skel/Desktop
			ADVERTENCIA "Removiendo enlace de escritorio Desktop en /etc/skel/ ..."
		fi

		# ¿Existe un enlace simbólico llamado Escritorio?
		# ¿Y una carpeta llamada Desktop?
		if [ -h /etc/skel/Escritorio ] && [ -d /etc/skel/Desktop ]; then
			# Borra el enlace simbólico
			rm -rf /etc/skel/Escritorio
			# y renombra la carpeta a Escritorio
			mv /etc/skel/Desktop /etc/skel/Escritorio
			ADVERTENCIA "Borrando enlace simbólico Escritorio y renombrando carpeta Desktop a Escritorio en /etc/skel/ ..."
		fi

		# ¿Existen dos directorios con el mismo propósito?
		if [ -d /etc/skel/Escritorio ] && [ -d /etc/skel/Desktop ]; then
			# Mueve el contenido de Desktop a Escritorio
			if [ $( ls -1 /etc/skel/Desktop | wc -l ) -gt 0 ]; then
    				mv /etc/skel/Desktop/* /etc/skel/Escritorio/
			fi

			# Borra la carpeta Desktop
			rm -rf /etc/skel/Desktop
			ADVERTENCIA "Moviendo el contenido de la carpeta Desktop a Escritorio y borrando Desktop en /etc/skel/ ..."
		fi

	# Para cada usuario en /home/ ...
	for HOME_U in /home/*?; do

		# Obteniendo sólo el nombre del usuario
		USUARIO=$( basename ${HOME_U} )

		# Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
		if [ $( grep -c "${HOME_U}:.*:.*:.*:.*:.*:::" /etc/shadow ) == 1 ] \
		&& [ $( grep -c "${HOME_U}:.*:.*:.*:.*:.*:/bin/.*sh" /etc/passwd ) == 1 ] \
		&& [ -d ${HOME_U}/.config ] \
		&& [ -d ${HOME_U} ]; then

			# ¿No existe la carpeta Escritorio?
			if [ ! -d ${HOME_U}/Escritorio ]; then
				[ -h ${HOME_U}/Escritorio ] && rm -rf ${HOME_U}/Escritorio
				[ -f ${HOME_U}/Escritorio ] && rm -rf ${HOME_U}/Escritorio
				mkdir ${HOME_U}/Escritorio
				chown -R ${HOME_U}:${HOME_U} ${HOME_U}/Escritorio
				ADVERTENCIA "Creando carpeta Escritorio en ${HOME_U} ..."
			fi
			# ¿Existe un enlace simbólico llamado Desktop?
			# ¿Y una carpeta llamada Escritorio?
			if [ -h ${HOME_U}/Desktop ] && [ -d ${HOME_U}/Escritorio ]; then
				# Borra el enlace simbólico
				rm -f ${HOME_U}/Desktop
				ADVERTENCIA "Removiendo enlace de escritorio Desktop en ${HOME_U} ..."
			fi
			# ¿Existe un enlace simbólico llamado Escritorio?
			# ¿Y una carpeta llamada Desktop?
			if [ -h ${HOME_U}/Escritorio ] && [ -d ${HOME_U}/Desktop ]; then
				# Borra el enlace simbólico
				rm -f ${HOME_U}/Escritorio
				# y renombra la carpeta a Escritorio
				mv ${HOME_U}/Desktop ${HOME_U}/Escritorio
				chown -R ${HOME_U}:${HOME_U} ${HOME_U}/Escritorio
				ADVERTENCIA "Borrando enlace simbólico Escritorio y renombrando carpeta Desktop a Escritorio en ${HOME_U} ..."
			fi
			# ¿Existen dos directorios con el mismo propósito?
			if [ -d ${HOME_U}/Escritorio ] && [ -d ${HOME_U}/Desktop ]; then
				# Mueve el contenido de Desktop a Escritorio
			if [ $( ls -lah ${HOME_U}/Desktop | wc  -l ) -gt 0 ]; then
		    		mv ${HOME_U}/Desktop/* ${HOME_U}/Escritorio/
			fi
				chown -R ${HOME_U}:${HOME_U} ${HOME_U}/Escritorio
				# Borra la carpeta Desktop
				rm -rf ${HOME_U}/Desktop
				ADVERTENCIA "Moviendo el contenido de la carpeta Desktop a Escritorio y borrando Desktop en ${HOME_U} ..."
			fi

			# Configuremos XDG para que use como locale "es_VE" y
			# Escritorio como carpeta de usuario predeterminada

			echo "es_VE" > ${HOME_U}/.config/user-dirs.locale

cat <<EOF >${HOME_U}/.config/user-dirs.dirs
# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run
# Format is XDG_xxx_DIR="\$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.
#
XDG_DESKTOP_DIR="\$HOME/Escritorio"
XDG_DOWNLOAD_DIR="\$HOME/Descargas"
XDG_TEMPLATES_DIR="\$HOME/Plantillas"
XDG_PUBLICSHARE_DIR="\$HOME/Público"
XDG_DOCUMENTS_DIR="\$HOME/Documentos"
XDG_MUSIC_DIR="\$HOME/Música"
XDG_PICTURES_DIR="\$HOME/Imágenes"
XDG_VIDEOS_DIR="\$HOME/Videos"

EOF

			chown -R ${HOME_U}:${HOME_U} ${HOME_U}/.config

			# Actualicemos la configuración
			if [ -x "$( which xdg-user-dirs-update )" ]; then
				su ${HOME_U} --command "xdg-user-dirs-update"
				su ${HOME_U} --command "xdg-user-dirs-update --force"
				EXITO "Carpetas de usuario actualizadas para '"${HOME_U}"'"
			fi
	
		fi

	done

	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)

		ERROR "postinst no reconoce el argumento '"${1}"'" >&2
		exit 1

	;;

esac

#DEBHELPER#

exit 0
