#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-escritorio-gnome
# ARCHIVO: preinst
# DESCRIPCIÓN: Configura el sistema antes de la instalación del paquete.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#  (C) 2010 Diego Alberto Aguilera Zambrano <daguilera85@gmail.com>
#  (C) 2010 Carlos Alejandro Guerrero Mora <guerrerocarlos@gmail.com>
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-escritorio-gnome"

case ${1} in

	install|upgrade)

	# ¿Existe un enlace simbólico llamado Desktop?
	# ¿Y una carpeta llamada Escritorio?
	if [ -h /etc/skel/Desktop ] && [ -d /etc/skel/Escritorio ]
	then

		# Borra el enlace simbólico
		rm -f /etc/skel/Desktop

	# ¿Existe un enlace simbólico llamado Escritorio?
	# ¿Y una carpeta llamada Desktop?
	elif [ -h /etc/skel/Escritorio ] && [ -d /etc/skel/Desktop ]
	then

		# Borra el enlace simbólico
		rm -f /etc/skel/Escritorio

		# y renombra la carpeta a Escritorio
		mv /etc/skel/Desktop /etc/skel/Escritorio

	# ¿Existen dos directorios con el mismo propósito?
        elif [ -d /etc/skel/Escritorio ] && [ -d /etc/skel/Desktop ]
        then

		# Mueve el contenido de Desktop a Escritorio
		mv /etc/skel/Desktop/* /etc/skel/Escritorio/

		# Borra la carpeta Desktop
		rm -rf /etc/skel/Desktop

	fi

cat <<EOF >/etc/xdg/user-dirs.defaults
# Default settings for user directories
#
# The values are relative pathnames from the home directory and
# will be translated on a per-path-element basis into the users locale
DESKTOP=Escritorio
DOWNLOAD=Descargas
TEMPLATES=Templates
PUBLICSHARE=Público
DOCUMENTS=Documentos
MUSIC=Música
PICTURES=Imágenes
VIDEOS=Videos
# Another alternative is:
#MUSIC=Documents/Music
#PICTURES=Documents/Pictures
#VIDEOS=Documents/Videos

EOF

	# Para cada usuario en /home/ ...
	for usuario in /home/*? ;
	do

	# Obteniendo sólo el nombre del usuario
	usuario_min=$(basename ${usuario})

	# Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
	case $( grep ${usuario_min} /etc/shadow ) in

	'')
	# No hace nada si no se encuentra en /etc/shadow
	;;

	*)

	# ¿Existe un enlace simbólico llamado Desktop?
	# ¿Y una carpeta llamada Escritorio?
	if [ -h ${usuario}/Desktop ] && [ -d ${usuario}/Escritorio ]
	then

		# Borra el enlace simbólico
		rm -f ${usuario}/Desktop

	# ¿Existe un enlace simbólico llamado Escritorio?
	# ¿Y una carpeta llamada Desktop?
	elif [ -h ${usuario}/Escritorio ] && [ -d ${usuario}/Desktop ]
	then

		# Borra el enlace simbólico
		rm -f ${usuario}/Escritorio

		# y renombra la carpeta a Escritorio
		mv ${usuario}/Desktop ${usuario}/Escritorio

	# ¿Existen dos directorios con el mismo propósito?
        elif [ -d ${usuario}/Escritorio ] && [ -d ${usuario}/Desktop ]
        then

		# Mueve el contenido de Desktop a Escritorio
		mv ${usuario}/Desktop/* ${usuario}/Escritorio/

		# Borra la carpeta Desktop
		rm -rf ${usuario}/Desktop
	
	fi

	# Configuremos XDG para que use como locale "es_VE" y
	# Escritorio como carpeta de usuario predeterminada

	echo "es_VE" > ${usuario}/.config/user-dirs.locale

cat <<EOF >${usuario}/.config/user-dirs.dirs
# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run
# Format is XDG_xxx_DIR="$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.
#
XDG_DESKTOP_DIR="$HOME/Escritorio"
XDG_DOWNLOAD_DIR="$HOME/Descargas"
XDG_TEMPLATES_DIR="$HOME/Plantillas"
XDG_PUBLICSHARE_DIR="$HOME/Público"
XDG_DOCUMENTS_DIR="$HOME/Documentos"
XDG_MUSIC_DIR="$HOME/Música"
XDG_PICTURES_DIR="$HOME/Imágenes"
XDG_VIDEOS_DIR="$HOME/Videos"

EOF

	# Actualicemos la configuración
	xdg-user-dirs-update

	;;

	esac
	done
	;;

	abort-upgrade)
	;;

	*)
		echo "preinst no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
