#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-escritorio-gnome
# ARCHIVO: prerm
# DESCRIPCIÓN: Prepara el sistema para que el paquete sea removido.
# COPYRIGHT:
#  (C) 2010 Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#  (C) 2010 Diego Alberto Aguilera Zambrano <daguilera85@gmail.com>
#  (C) 2010 Carlos Alejandro Guerrero Mora <guerrerocarlos@gmail.com>
#  (C) 2010 Francisco Javier Vásquez Guerrero <franjvasquezg@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-escritorio-gnome"
VERDE="\033[1;34m"
ROJO="\033[0;31m"
FIN="\033[0m"

case ${1} in

	remove|upgrade|deconfigure)

	echo -e ${VERDE}"===== Revirtiendo script de Lennart Poettering ====="${FIN}

        # Para cada usuario en /home/ ...
        for usuario in /home/*? ;
        do

                # Obteniendo sólo el nombre del usuario
                usuario_min=$(basename ${usuario})

                # Y en caso de que el usuario sea un usuario activo (existente en /etc/shadow) ...
                case $(grep ${usuario_min} /etc/shadow) in

                '')
                # No hace nada si no se encuentra en /etc/shadow
                ;;

                *)

                BASHRC_F="/home/${usuario_min}/.bashrc"

		[ -e ${BASHRC_F}.respaldo ] && mv ${BASHRC_F}.respaldo ${BASHRC_F}
		;;

		esac
	done

	RCLOCAL_F="/etc/rc.local"
	[ -e ${RCLOCAL_F}.respaldo ] && mv ${RCLOCAL_F}.respaldo ${RCLOCAL_F}

	CGROUP_F="/usr/local/sbin/cgroup_clean"
	rm -rf ${CGROUP_F}

	;;

	failed-upgrade)
	;;

	*)

		echo "prerm no reconoce el argumento '"${1}"'" >&2
		exit 1
	;;

esac

#DEBHELPER#

exit 0
